### ISSUE TITLE
File: "PlusTransverseProcessEnhancerTestData.mha" is not found

### ISSUE THREAD

**Issue by carlos-luque** [PlusToolkit/PlusLibData#5]
The file "PlusTransverseProcessEnhancerTestData.mha" is not found from the folder _Images_. This generates the test "vtkPlusTransverseProcessEnhancerTest" fails. 

We are copying the error:

24/108 Test  #24: vtkPlusTransverseProcessEnhancerTest .............................................***Failed  Error regular expression found in output. Regex=[ERROR] 
 0.02 sec
System start timestamp: 1.50771e+09
Software version: Plus-2.5.0.ba69432 - Linux
|ERROR|000.001516| Image with relative path '.../PlusLibData/TestImages/PlusTransverseProcessEnhancerTestData.mha' cannot be found neither r
elative to image directory (.../PlusLibData/TestImages) nor relative to device set configuration file directory (.../PlusLibData)) nor to device set configuration directory (.../PlusLibData/ConfigFiles) nor the current working directory directory (.../PlusLib/build/src/PlusImageProcessing/Testing)| in .../PlusLib/src/PlusCommon/vtkPl
usConfig.cxx(887)
|ERROR|000.001569| Cannot find sequence metafile: .../PlusLibData/TestImages/PlusTransverseProcessEnhancerTestData.mha| in .../PlusLibFork/PlusLib/src/PlusCommon/vtkPlusTrackedFrameList.cxx(485)

**Comment by adamrankin** [comment]
I am going to close this issue as we are tracking it here:

https://github.com/PlusToolkit/PlusLib/issues/194
